
export const booksOfTheBible = [
    { englishName: 'Genesis', swahiliName: 'Mwanzo', chapters: 50 },
    { englishName: 'Exodus', swahiliName: 'Kutoka', chapters: 40 },
    { englishName: 'Leviticus', swahiliName: 'Walawi', chapters: 27 },
    { englishName: 'Numbers', swahiliName: 'Hesabu', chapters: 36 },
    { englishName: 'Deuteronomy', swahiliName: 'Kumbukumbu la Torati', chapters: 34 },
    { englishName: 'Joshua', swahiliName: 'Yoshua', chapters: 24 },
    { englishName: 'Judges', swahiliName: 'Waamuzi', chapters: 21 },
    { englishName: 'Ruth', swahiliName: 'Ruthu', chapters: 4 },
    { englishName: '1 Samuel', swahiliName: '1 Samweli', chapters: 31 },
    { englishName: '2 Samuel', swahiliName: '2 Samweli', chapters: 24 },
    { englishName: '1 Kings', swahiliName: '1 Wafalme', chapters: 22 },
    { englishName: '2 Kings', swahiliName: '2 Wafalme', chapters: 25 },
    { englishName: '1 Chronicles', swahiliName: '1 Mambo ya Nyakati', chapters: 29 },
    { englishName: '2 Chronicles', swahiliName: '2 Mambo ya Nyakati', chapters: 36 },
    { englishName: 'Ezra', swahiliName: 'Ezra', chapters: 10 },
    { englishName: 'Nehemiah', swahiliName: 'Nehemia', chapters: 13 },
    { englishName: 'Esther', swahiliName: 'Esta', chapters: 10 },
    { englishName: 'Job', swahiliName: 'Ayubu', chapters: 42 },
    { englishName: 'Psalms', swahiliName: 'Zaburi', chapters: 150 },
    { englishName: 'Proverbs', swahiliName: 'Mithali', chapters: 31 },
    { englishName: 'Ecclesiastes', swahiliName: 'Mhubiri', chapters: 12 },
    { englishName: 'Song of Solomon', swahiliName: 'Wimbo Ulio Bora', chapters: 8 },
    { englishName: 'Isaiah', swahiliName: 'Isaya', chapters: 66 },
    { englishName: 'Jeremiah', swahiliName: 'Yeremia', chapters: 52 },
    { englishName: 'Lamentations', swahiliName: 'Maombolezo', chapters: 5 },
    { englishName: 'Ezekiel', swahiliName: 'Ezekieli', chapters: 48 },
    { englishName: 'Daniel', swahiliName: 'Danieli', chapters: 12 },
    { englishName: 'Hosea', swahiliName: 'Hosea', chapters: 14 },
    { englishName: 'Joel', swahiliName: 'Yoeli', chapters: 3 },
    { englishName: 'Amos', swahiliName: 'Amosi', chapters: 9 },
    { englishName: 'Obadiah', swahiliName: 'Obadia', chapters: 1 },
    { englishName: 'Jonah', swahiliName: 'Yona', chapters: 4 },
    { englishName: 'Micah', swahiliName: 'Mika', chapters: 7 },
    { englishName: 'Nahum', swahiliName: 'Nahumu', chapters: 3 },
    { englishName: 'Habakkuk', swahiliName: 'Habakuki', chapters: 3 },
    { englishName: 'Zephaniah', swahiliName: 'Sefania', chapters: 3 },
    { englishName: 'Haggai', swahiliName: 'Hagai', chapters: 2 },
    { englishName: 'Zechariah', swahiliName: 'Zekaria', chapters: 14 },
    { englishName: 'Malachi', swahiliName: 'Malaki', chapters: 4 },
    { englishName: 'Matthew', swahiliName: 'Mathayo', chapters: 28 },
    { englishName: 'Mark', swahiliName: 'Marko', chapters: 16 },
    { englishName: 'Luke', swahiliName: 'Luka', chapters: 24 },
    { englishName: 'John', swahiliName: 'Yohana', chapters: 21 },
    { englishName: 'Acts', swahiliName: 'Matendo', chapters: 28 },
    { englishName: 'Romans', swahiliName: 'Warumi', chapters: 16 },
    { englishName: '1 Corinthians', swahiliName: '1 Wakorintho', chapters: 16 },
    { englishName: '2 Corinthians', swahiliName: '2 Wakorintho', chapters: 13 },
    { englishName: 'Galatians', swahiliName: 'Wagalatia', chapters: 6 },
    { englishName: 'Ephesians', swahiliName: 'Waefeso', chapters: 6 },
    { englishName: 'Philippians', swahiliName: 'Wafilipi', chapters: 4 },
    { englishName: 'Colossians', swahiliName: 'Wakolosai', chapters: 4 },
    { englishName: '1 Thessalonians', swahiliName: '1 Wathesalonike', chapters: 5 },
    { englishName: '2 Thessalonians', swahiliName: '2 Wathesalonike', chapters: 3 },
    { englishName: '1 Timothy', swahiliName: '1 Timotheo', chapters: 6 },
    { englishName: '2 Timothy', swahiliName: '2 Timotheo', chapters: 4 },
    { englishName: 'Titus', swahiliName: 'Tito', chapters: 3 },
    { englishName: 'Philemon', swahiliName: 'Filemoni', chapters: 1 },
    { englishName: 'Hebrews', swahiliName: 'Waebrania', chapters: 13 },
    { englishName: 'James', swahiliName: 'Yakobo', chapters: 5 },
    { englishName: '1 Peter', swahiliName: '1 Petro', chapters: 5 },
    { englishName: '2 Peter', swahiliName: '2 Petro', chapters: 3 },
    { englishName: '1 John', swahiliName: '1 Yohana', chapters: 5 },
    { englishName: '2 John', swahiliName: '2 Yohana', chapters: 1 },
    { englishName: '3 John', swahiliName: '3 Yohana', chapters: 1 },
    { englishName: 'Jude', swahiliName: 'Yuda', chapters: 1 },
    { englishName: 'Revelation', swahiliName: 'Ufunuo', chapters: 22 },
];
