
export const booksOfTheBible = [
    { englishName: 'Genesis', chapters: 50 },
    { englishName: 'Exodus', chapters: 40 },
    { englishName: 'Leviticus', chapters: 27 },
    { englishName: 'Numbers', chapters: 36 },
    { englishName: 'Deuteronomy', chapters: 34 },
    { englishName: 'Joshua', chapters: 24 },
    { englishName: 'Judges', chapters: 21 },
    { englishName: 'Ruth', chapters: 4 },
    { englishName: '1 Samuel', chapters: 31 },
    { englishName: '2 Samuel', chapters: 24 },
    { englishName: '1 Kings', chapters: 22 },
    { englishName: '2 Kings', chapters: 25 },
    { englishName: '1 Chronicles', chapters: 29 },
    { englishName: '2 Chronicles', chapters: 36 },
    { englishName: 'Ezra', chapters: 10 },
    { englishName: 'Nehemiah', chapters: 13 },
    { englishName: 'Esther', chapters: 10 },
    { englishName: 'Job', chapters: 42 },
    { englishName: 'Psalms', chapters: 150 },
    { englishName: 'Proverbs', chapters: 31 },
    { englishName: 'Ecclesiastes', chapters: 12 },
    { englishName: 'Song of Solomon', chapters: 8 },
    { englishName: 'Isaiah', chapters: 66 },
    { englishName: 'Jeremiah', chapters: 52 },
    { englishName: 'Lamentations', chapters: 5 },
    { englishName: 'Ezekiel', chapters: 48 },
    { englishName: 'Daniel', chapters: 12 },
    { englishName: 'Hosea', chapters: 14 },
    { englishName: 'Joel', chapters: 3 },
    { englishName: 'Amos', chapters: 9 },
    { englishName: 'Obadiah', chapters: 1 },
    { englishName: 'Jonah', chapters: 4 },
    { englishName: 'Micah', chapters: 7 },
    { englishName: 'Nahum', chapters: 3 },
    { englishName: 'Habakkuk', chapters: 3 },
    { englishName: 'Zephaniah', chapters: 3 },
    { englishName: 'Haggai', chapters: 2 },
    { englishName: 'Zechariah', chapters: 14 },
    { englishName: 'Malachi', chapters: 4 },
    { englishName: 'Matthew', chapters: 28 },
    { englishName: 'Mark', chapters: 16 },
    { englishName: 'Luke', chapters: 24 },
    { englishName: 'John', chapters: 21 },
    { englishName: 'Acts', chapters: 28 },
    { englishName: 'Romans', chapters: 16 },
    { englishName: '1 Corinthians', chapters: 16 },
    { englishName: '2 Corinthians', chapters: 13 },
    { englishName: 'Galatians', chapters: 6 },
    { englishName: 'Ephesians', chapters: 6 },
    { englishName: 'Philippians', chapters: 4 },
    { englishName: 'Colossians', chapters: 4 },
    { englishName: '1 Thessalonians', chapters: 5 },
    { englishName: '2 Thessalonians', chapters: 3 },
    { englishName: '1 Timothy', chapters: 6 },
    { englishName: '2 Timothy', chapters: 4 },
    { englishName: 'Titus', chapters: 3 },
    { englishName: 'Philemon', chapters: 1 },
    { englishName: 'Hebrews', chapters: 13 },
    { englishName: 'James', chapters: 5 },
    { englishName: '1 Peter', chapters: 5 },
    { englishName: '2 Peter', chapters: 3 },
    { englishName: '1 John', chapters: 5 },
    { englishName: '2 John', chapters: 1 },
    { englishName: '3 John', chapters: 1 },
    { englishName: 'Jude', chapters: 1 },
    { englishName: 'Revelation', chapters: 22 },
];
